name_test = ("Задача 1 «Сложная сдача».")
name = ('Товар', "Черешня")
cost_name = ("Цена")
cost = (34)
val = ("руб.")
total_name = ("Количество")
total = (4.5)
money = (500)
sum = (cost) * (total)
change = float (money) - (sum)
print (name_test)
print( "Сдача", change, val)
# Конец задачи
print ("_____________________________")

name_test =("Задача 2 «Сдача всем».")
name = ("Макароны")
cost_name = ("Цена")
cost = float(450)
val = ("руб.")
total_name = ("Количество")
total = (3.8)
vag = ("кг.")
money_name = ("Внесено покупателем")
money = (5000)
sum = (cost) * (total)
change = float (money) - (sum)
print (name_test)
print (name)
print (cost_name,cost, val)
print (total_name,total, vag)
print ("Сумма покупки", sum, val)
print (money_name, money,val)
print ("Cдача", change, val)
# Конец задачи
print ("_____________________________")
name_test =("Задача 3 «Самая простая задача на свете».")
name =(7)
name_str =("Купи конструктор!\n")
print (name_test)
print (name_str * name)
# Конец задачи
print ("_____________________________")
name_test =("Задача 4 «Автоматизируем простоту!».")
name = (5)
name2 = ("python\n")
print (name_test)
print ("Обожаю писать")
print (name2 * name)
# Конец задачи
print ("_____________________________")